# Generated by Django 6.0.3 on 2026-03-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash_on_delivery', 'Cash on Delivery')], default='mpesa', max_length=50),
        ),
    ]
